const types = {
  UPDATE: "UPDATE",
  UPDATE_ONE: "UPDATE_ONE",
  SET: "SET",
  REMOVE: "REMOVE",
  CREATE: "CREATE",
  RESET: "RESET",
  SET_FILES: "SET_FILES",
  SET_ANSWERS: "SET_ANSWERS",
  SET_RULES: "SET_RULES",
  SET_RULE_GROUPS: "SET_RULE_GROUPS",
};
module.exports = types;
